Revert [llvm] annotate ABIBreakingChecks symbols for DLL export (#147965)
This patch reverts commit e484ece15b05438c66212a8e67599178f6396427. The
change introduced a cyclic dependency:
```
fatal error: cyclic dependency in module 'LLVM_Utils': LLVM_Utils -> LLVM_Config_ABI_Breaking -> LLVM_Utils
```

See failure log at
https://green.lab.llvm.org/job/llvm.org/job/clang-stage2-Rthinlto/976/console.