[mlir] Fix a warning
This patch fixes:

  mlir/lib/Transforms/Utils/DialectConversion.cpp:1686:14: error:
  unused variable 'newParentOp' [-Werror,-Wunused-variable]