[MLIR/Utils] Add missing dep on Arith dialect (#146834)
Fix the following compile error when building libMLIRDialectUtils.a
only:

In file included from
mlir/include/mlir/Dialect/Utils/ReshapeOpsUtils.h:17,
                 from mlir/lib/Dialect/Utils/ReshapeOpsUtils.cpp:9:
mlir/include/mlir/Dialect/Arith/IR/Arith.h:28:10:
fatal error: mlir/Dialect/Arith/IR/ArithOpsDialect.h.inc: No such file
or directory

ArithDialect dependency is now needed since
95890d5684e883328be3c9f0f5cad7f87e90e0b1 to create arith.muli op.