[X86] Fix an unused-variable warnig (NFC)
/llvm-project/llvm/lib/Target/X86/X86CallingConv.cpp:392:12:
error: unused variable 'NumRegs' [-Werror,-Wunused-variable]
  unsigned NumRegs = PendingMembers.size();
           ^
1 error generated.