Revert "[RISCV] AddEdge between mask producer and user of V0 (#146855)"
This reverts commit 6ac54fdcf92bad3b8e14aae2fc4f1a2f7713d687.

As noted
<https://github.com/llvm/llvm-project/pull/146855#issuecomment-3061784904>
this causes compile errors for several RVV configurations:

    fatal error: error in backend: SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)