[AArch64] Fix a warning
This patch fixes:

  llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:19079:7: error:
  unused variable 'VT' [-Werror,-Wunused-variable]