[mlir][python] Fix ir.Value type to not break other types (#167930)
Change in https://github.com/llvm/llvm-project/pull/166148 caused breaks
for some other types.
Specifically this error was seen in a downstream project
```
 _ods_ir.OpOperandList[_ods_ir.IntegerType]:

TypeError: type 'iree.compiler._mlir_libs._mlir.ir.OpOperandList' is not subscriptable

```
This PR tries to make those changes not affect the other types

---------

Signed-off-by: Nirvedh Meshram <nirvedh@gmail.com>