[polly] Fix unused variable warnings
This patch fixes:

  polly/lib/Transform/ScheduleOptimizer.cpp:935:17: error: unused
  variable 'File' [-Werror,-Wunused-variable]

  polly/lib/Transform/ScheduleOptimizer.cpp:936:9: error: unused
  variable 'Line' [-Werror,-Wunused-variable]

  polly/lib/Transform/ScheduleOptimizer.cpp:937:17: error: unused
  variable 'Msg' [-Werror,-Wunused-variable]