[CodeGen] Remove unused variable (NFC)
/llvm-project/llvm/lib/CodeGen/SafeStack.cpp:666:11:
 error: unused variable 'Ty' [-Werror,-Wunused-variable]
    Type *Ty = AI->getAllocatedType();
          ^
1 error generated.