Fix build break in RISCV unit tests
/usr/bin/ld: unittests/Target/RISCV/CMakeFiles/RISCVTests.dir/RISCVSelectionDAGTest.cpp.o: undefined reference to symbol '_ZN4llvm19parseAssemblyStringENS_9Stri
ngRefERNS_12SMDiagnosticERNS_11LLVMContextEPNS_11SlotMappingE'
/usr/bin/ld: lib/libLLVMAsmParser.so.22.0git:
error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status