Revert "[flang][OpenMP] Analyze objects in OmpObjectList on clauses (#155424)"
This reverts commit 59b58685cab98920469e110d6abd534d02de3940.

This breaks gfortran test suite:

```
error: Semantic errors in gfortran/regression/gomp/pr80918.f90
gfortran/regression/gomp/pr80918.f90:6:27: error: Whole assumed-size array 'a' may not appear here without subscripts
    !$omp task depend(inout:a)
                            ^
gfortran/regression/gomp/pr80918.f90:5:14: Declaration of 'a'
    integer :: a(*)
               ^
```

The error appears to be legitimate.