libc: Prefix Rounding Control Error enum to avoid conflict in windows build (#172562)
Similar to 02682a81fe3e

Somehow conflict with define in wingdi.h.

Fix build failures:
...FPUtil\x86_64\fenv_x86_common.h(78,29): error: expected member name
or
';' after declaration specifiers

78 |   static constexpr uint16_t ERROR = 0xFFFF;
         |   ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
c:\Program files (x86)\Windows
Kits\10\include\10.0.22000.0\um\wingdi.h(118,29):
note: expanded from macro 'ERROR'
      118 | #define ERROR               0
          |